[tool.poetry]
name = "TinyCTA"
version = "0.0.0"
description = "..."
authors = ["Thomas Schmelzer"]
readme = "README.md"
repository = "https://github.com/tschm/TinyCTA"
packages = [{include = "tinycta"}]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
pandas = "*"
numpy = "*"
plotly = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=1.6.0"]
build-backend = "poetry.masonry.api"
