name: pre-commit

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.17
        with:
          source-folder: 'tinycta'
          tests-folder: 'tests'
          coveralls: 'true'

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/pre-commit@v2.1.0

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/deptry@v2.0.17
        with:
          source-folder: 'tinycta'
